algorand/js-algorand-sdk

src/client/algod.js
This pull reqyest adds a `transactionById` client facing function which results in the
`/v1/transaction/${txId}` endpoint being requested.
=> client/algod: adds transactionById function

examples/webapp/test.html, examples/webapp/test.js
fixes for js and html files in sample web app, added in testnet dispensary and transaction fixes
=> Russ fix sample 2 w js and html fixes

examples/webapp/test.js
=> Russ fix sample

README.md, src/client/algod.js, src/encoding/encoding.js, src/main.js, src/transaction.js, tests/5.Transaction.js, tests/7.AlgoSDK.js
Two API as other SDKs: computeGroupID, assignGroupID, unit tests, and verification against goal clerk.
=> Groups support

README.md, src/client/algod.js, src/main.js, src/transaction.js, tests/5.Transaction.js, tests/7.AlgoSDK.js
Adds assetURL and similar. Handles assetName and similar as strings. Double checked `README.md`, looks like nothing much needs updating there.
Added `golden` tests to `AlgoSDK.js`.
https://github.com/algorand/js-algorand-sdk/issues/68
=> Add support for new asset fields. Also, add golden tests.

src/client/algod.js
To keep the functionality on par with all the other methods
=> Added optional headers parameter to assetInformation

src/logic/logic.js, tests/8.LogicSig.js
=> Fix Uvarint name

src/transaction.js
https://github.com/algorand/js-algorand-sdk/issues/84
=> Refuse to compute group id for too-large groups

src/logic/logic.js, src/logicTemplates/periodicpayment.js, tests/8.LogicSig.js
This template implements `periodic-payment.teal.impl` from `go-algorand`.
Automatic unit/sdk testing. Added a golden test for program and address.
https://github.com/algorand/js-algorand-sdk/issues/98
=> Periodic payment TEAL template

src/logicTemplates/htlc.js, src/logicTemplates/limitorder.js, tests/8.LogicSig.js
This template implements `limit-order-a.teal.impl` from `go-algorand`.
Automatic unit/sdk testing. Added a golden test for program and address.
https://github.com/algorand/js-algorand-sdk/issues/99
https://github.com/algorand/go-algorand-sdk/pull/101
=> Limit order TEAL template

src/client/v2/indexer/lookupAccountTransactions.js, src/client/v2/indexer/lookupAssetTransactions.js, tests/cucumber/steps/stepdefs.js
https://github.com/algorand/algorand-sdk-testing/pull/70
=> Comply with algorand-sdk-testing#70

Makefile, src/client/v2/indexer/searchAccounts.js, src/client/v2/indexer/searchForApplications.js, src/client/v2/indexer/searchForTransactions.js, tests/cucumber/steps/stepdefs.js
This PR proposes to add tests for @applications.verified and @indexer.applications. Tests pass locally, waiting for Travis approval.
=> Test updates: @applications.verified, @indexer.applications

src/client/client.js
Added helper function that can be easily expanded for additional responses formats if needed.
=> Added helper function to correctly set Accept on GETs

tests/cucumber/docker/run_docker.sh
I meant to delete this code before merging #228.
=> Remove unnecessary code from docker script

package-lock.json, package.json
tweetnacl 1.0.1 -> 1.0.3
superagent 4.1.0 -> 6.1.0
=> Update dependencies to latest for release

src/client/v2/algod/versions.js
Fixes a mistake in the v2 client version endpoint.
Fixes #256.
=> Fix version endpoint

src/mnemonic/mnemonic.ts, src/mnemonic/wordlists/english.ts
=> Migrate `mnemonic.js` to TypeScript

examples/webapp/test.html, package-lock.json, package.json, tsconfig-browser.json, tsconfig-cjs.json, tsconfig-esm.json, tsconfig-umd.json, tsconfig.json, webpack.config.js
* Build optimal distribution files for `CommonJS`, `ESM`, and browser bundles.
* Add `”types”` option to `package.json` to expose TypeScript declaration files
* Specify `”module”` path for ESM module support
Closes #322.
=> Improve build steps for TypeScript migration

package-lock.json, package.json, src/client/client.ts, tests/9.Client.ts, webpack.config.js
=> Use node’s `url` module for URL construction in the HTTPClient constructor

src/client/v2/algod/models/types.ts, templates/model.vm
=> Add comment documentation to generated class properties

Makefile, templates/Dockerfile, templates/generate.sh
This PR adds files to instruct the automated code generator on how to generate and format code for this repository.
Closes #345.
=> Support automated code generation by including a `Dockerfile` configuration in the `templates` directory

FAQ.md, Makefile, README.md, src/client/v2/algod/algod.ts, src/client/v2/algod/compile.ts, src/client/v2/algod/models/types.ts, templates/Dockerfile, templates/generate.sh, templates/model.vm
Currently `release/1.9.0` contains the code for the beta release `1.9.0-beta.1`. This PR will merge any additional updates from the `develop` branch that we would like to release under 1.9.0 proper.
This should not be merged until 1.9.0 is ready to release.
=> Sync updates for 1.9.0

README.md, package.json
Specify the minimum version of TypeScript needed to use this package, plus some minor description changes.
Closes #354.
=> Specify TS version in README

README.md
mostly node/Node/node.js > Node.js
also added few references to download pages for node/typescript - this also helps for SEO but is unrelated
=> inconsistencies, grammar, references

Makefile, src/client/v2/algod/models/types.ts, src/main.ts, src/makeTxn.ts, src/transaction.ts, tests/5.Transaction.js, tests/cucumber/steps/steps.js
This PR is to support creating transactions with a fee under mintxnfee since other txns in the group will be paying.
=> Fee pooling SDK change

src/logic/logic.ts, tests/8.LogicSig.js
SDK Updates for dynamic opcode accounting, backward jumps, loops, callsub, retsub
=> Dynamic opcode

src/types/transactions/encoded.ts
=> add `msig` and `lsig` fields to `EncodedSignedTransaction` type

src/logic/logic.ts, src/logicsig.ts, src/main.ts, src/multisig.ts, src/types/transactions/encoded.ts, tests/6.Multisig.ts, tests/8.LogicSig.ts
Implement the improvements from https://github.com/algorand/go-algorand-sdk/pull/230
This also closes #365
=> Signing support for rekeying to LogicSig/MultiSig account

CHANGELOG.md, package-lock.json, package.json, src/client/v2/algod/models/types.ts, src/transaction.ts, tests/5.Transaction.js
- Properly decode transaction extra pages field (#419)
=> DO NOT MERGE - js-algorand-sdk v1.11.1

src/main.ts
For some reason a PR got through which doesn't pass our formatter. This fixed it.
=> Fix unformatted code

src/transaction.ts, tests/5.Transaction.js
Adding message to help debug when amount/assetAmount is large as in #500
=> adding note to use bigint

CHANGELOG.md, README.md, package-lock.json, package.json, src/client/client.ts, src/dryrun.ts, src/transaction.ts, tests/5.Transaction.js, tests/9.Client.ts
- Add app creator to dryrun request (#499)
- Adding note to use bigint to help debug when amount/assetAmount is large (#501)
- Fix JSON decoding (#502)
=> js-algorand-sdk v1.13.1

CHANGELOG.md, README.md, package-lock.json, package.json, src/client/client.ts, src/client/v2/indexer/lookupAccountTransactions.ts, src/client/v2/indexer/lookupAssetByID.ts, src/client/v2/jsonrequest.ts, src/makeTxn.ts, src/types/utils.ts, tests/cucumber/docker/run_docker.sh
- Add stateproof keyreg field (#463)
- Implement C2C tests (#498)
- Moving from travis to circleci (#507)
- Add installation instructions for vite users (#512)
- Update langspec for TEAL 6 (#518)
- Docs for `lookupAssetByID` and `lookupAccountTransactions` (#516)
- Make FromObject parameter IntelliSense human readable (#528)
- Bump url-parse from 1.5.1 to 1.5.8 (#529)
- Use HTTP request format arg to determine response type (#532)
- Update chromedriver (#535)
=> FOR REVIEW ONLY - js-algorand-sdk v1.14.0

src/client/v2/indexer/searchForApplications.ts
=> Fix searchForApplications filter by creator parameter type

CHANGELOG.md, README.md, package-lock.json, package.json, src/client/v2/indexer/searchForApplications.ts
- Support unlimited assets REST API changes. (#527)
- Fix app creation createDryrun error (#539)
- Fix cucumber tests for asset lookup step (#540)
- Fix searchForApplications filter by creator parameter type. (#546)
=> FOR REVIEW ONLY - js-algorand-sdk v1.15.0

src/dryrun.ts
We should be including the app address for foreign apps
=> adding foreign app addr to dryrun

src/composer.ts, tests/cucumber/steps/steps.js
Adds the ABIMethod called into the ABIResult object we return for each app call transaction
=> Add method to abi results

CHANGELOG.md, FAQ.md, README.md, package-lock.json, package.json, src/client/urlTokenBaseHTTPClient.ts, src/dryrun.ts, src/utils/utils.ts, tests/2.Encoding.js, webpack.config.js
* Properly set maxWidth in trace by @joe-p in https://github.com/algorand/js-algorand-sdk/pull/593
* fix: safe intDecoding by @AlgoDoggo in https://github.com/algorand/js-algorand-sdk/pull/599
* Remove code that relies on node's path module by @bmdelacruz in https://github.com/algorand/js-algorand-sdk/pull/598
* @AlgoDoggo made their first contribution in https://github.com/algorand/js-algorand-sdk/pull/599
* @bmdelacruz made their first contribution in https://github.com/algorand/js-algorand-sdk/pull/598
**Full Changelog**: https://github.com/algorand/js-algorand-sdk/compare/v1.18.0...v1.18.1
=> FOR REVIEW ONLY - Release v1.18.1

src/logic/logic.ts, tests/8.LogicSig.ts
Applies feedback from https://github.com/algorand/go-algorand/issues/4125 to consolidate TEAL and AVM versions.
=> AVM:  Consolidate TEAL and AVM versions

tests/cucumber/unit.tags
Updating unit tags to include test for ParticipationUpdates field. cucumber test update [PR](https://github.com/algorand/algorand-sdk-testing/pull/234.)
=> enhancement: add unit test for ParticipationUpdates field

src/makeTxn.ts, tests/cucumber/steps/steps.js
Child PR to #604
Changes the order of arguments to avoid introducing a breaking change with the new box arguments.
=> Re-order box args to avoid breaking changes

.test-env, CHANGELOG.md, Makefile, README.md, package.json, src/client/algod.js, src/client/v2/algod/algod.ts, src/client/v2/algod/getBlockHash.ts, src/client/v2/indexer/lookupBlock.ts, src/client/v2/indexer/searchAccounts.ts, test-harness.sh, tests/cucumber/steps/steps.js, tests/cucumber/unit.tags
Merge develop into feature/box-storage.
```
$ git merge develop
Auto-merging .test-env
Auto-merging src/client/v2/algod/algod.ts
CONFLICT (content): Merge conflict in src/client/v2/algod/algod.ts
Auto-merging tests/cucumber/steps/steps.js
Auto-merging tests/cucumber/unit.tags
Automatic merge failed; fix conflicts and then commit the result.
```
This was a pretty straightforward merge, as the only conflict requiring attention was the imports from `src/client/v2/algod/algod.ts`
=> Box storage merge develop

.circleci/config.yml, .npmrc, package-lock.json, package.json, src/client/urlTokenBaseHTTPClient.ts, src/client/v2/algod/algod.ts, src/client/v2/algod/models/types.ts, tests/9.Client.ts, tests/cucumber/docker/Dockerfile, tests/cucumber/steps/steps.js
Refreshes the parent branch with a merge from `develop` and regenerates sources to take in upstream go-algorand + indexer changes one final time prior to merging the parent branch.
=> Refresh integration branch before merge

CHANGELOG.md, README.md, package-lock.json, package.json
=> Release: merge back into develop Release/v1.23.0

CHANGELOG.md, README.md, package-lock.json, package.json, src/abi/abi_type.ts, src/client/v2/algod/models/types.ts, src/multisig.ts, tests/10.ABI.ts, tests/cucumber/steps/steps.js
* Bug-Fix: encode ABI string with non-ASCII characters by @ahangsu in https://github.com/algorand/js-algorand-sdk/pull/700
* Tests: Migrate v1 algod dependencies to v2 in cucumber tests by @algochoi in https://github.com/algorand/js-algorand-sdk/pull/693
* REST API:  Add KV counts to NodeStatusResponse by @michaeldiamant in https://github.com/algorand/js-algorand-sdk/pull/696
* Fix: createMultisigTransaction name in comments by @nullun in https://github.com/algorand/js-algorand-sdk/pull/694
* Enhancement: allowing zero-length static array by @ahangsu in https://github.com/algorand/js-algorand-sdk/pull/698
* ABI:  Refactor ABI encoding test to round-trip by @michaeldiamant in https://github.com/algorand/js-algorand-sdk/pull/701
* @nullun made their first contribution in …
=> FOR REVIEW ONLY - Release v1.24.0

.prettierignore, CODE_OF_CONDUCT.md
=> community: Create CODE_OF_CONDUCT.md

examples/asa.ts, src/client/v2/algod/getLedgerStateDelta.ts, src/client/v2/algod/getLedgerStateDeltaForTransactionGroup.ts, src/client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.ts, tests/cucumber/unit.tags
Add msgp query arg to deltas endpoints.
=> algod: Add json query arg to delta endpoints

v2_TO_v3_MIGRATION_GUIDE.md
Update migration guide with changes from #876
=> Migration guide update for #876

Makefile, src/client/v2/algod/models/types.ts, src/client/v2/indexer/models/types.ts, src/transaction.ts, src/types/transactions/base.ts, src/types/transactions/encoded.ts, src/types/transactions/heartbeat.ts, src/types/transactions/index.ts, tests/5.Transaction.js, tests/cucumber/steps/steps.js, tests/cucumber/unit.tags
Add heartbeat txn support. Note, this change includes models regenerated in https://github.com/algorand/js-algorand-sdk/pull/917 (i.e. subsequent PR)
1. Added golden txn test
2. Added cross sdk tests
=> Incentives: Support heartbeat transaction (v2.9)
