- src/bid.js
- src/encoding/address.js
- src/encoding/encoding.js
- src/main.js
- src/mnemonic/mnemonic.js
- src/nacl/naclWrappers.js
- src/utils/utils.js
For consistency, I added indentation and whitespace for some codes.
After this PR merged, following rules will be applied:
1. Add a space between key and value in object.
`{ key:value }` (X)
`{ key: value }` (O)
2. Add a space between parenthesis and curly braces.
`signBid(sk){` (X)
`signBid(sk) {` (O)
3. Add a space between operator and operands.
`nacl.HASH_BYTES_LENGTH-ALGORAND_CHECKSUM_BYTE_LENGTH` (X)
`nacl.HASH_BYTES_LENGTH - ALGORAND_CHECKSUM_BYTE_LENGTH` (O)
4. Add a comma between values.
`this.tag = Buffer.from([97,66])`  (X)
`this.tag = Buffer.from([97, 66])` (O)
5. Add a space between reserved word `if` and parenthesis.
`if(...)` (X)
`if (...)` (O)
6. Add a space between reserved word `for` and parenthesis.
`for(...)` (X)
`for (...)` (O)
7. Add a space between reserved word …
> Add indentation for consistency

- src/client/kmd.js
Previously, KMD passed four args to `client.HTTPClient`. However, `client.HTTPClient` expects three args, the first of which is a dict. This PR fixes the `Kmd` so it constructs its HTTP Client properly.
This change is necessary for the GOAL2-501 "sign a transaction using kmd in the javascript SDK" ticket, but additional work is needed to complete that.
> KMDClient properly provides a dict to first arg of HTTPClient

- src/transaction.js
Comparing the behaviour between SDK's, the field **note** seems to be optional though I wasn't able to let it undefined without the SDK throwing an error.
Assigning this as default will comply with the expected behaviour.
Error before this fix:
```bash
> algosdk.signTransaction(tx_object,sk.sk)
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
at Function.from (buffer.js:207:11)
at Transaction.get_obj_for_encoding (/home/fscucchiero/repos/algorand-api-backend/node_modules/algosdk/src/transaction.js:43:28)
at Transaction.toByte (/home/fscucchiero/repos/algorand-api-backend/node_modules/algosdk/src/transaction.js:72:37)
at Transaction.bytesToSign …
```
> Declaring note if undefined.

- README.md
- package-lock.json
- package.json
Old package-lock has implicit dependency to fsevents-1.2.7
that is not compatible with new nodejs
> Update package-lock to enable local build with node 12.10

- src/transaction.js
- tests/5.Transaction.js
- tests/7.AlgoSDK.js
This PR proposes to add asset transfer support to the javascript SDK, enabling: asset acceptance, asset transferral, asset clawback, asset mint, and asset burn.
Added a serialize/deserialize test to `Transaction.js`
> Add Asset Transfer ("axfer") transactions 

- src/client/algod.js
- src/client/client.js
Adds support for multiple different headers on the algod client and in all of the internal methods.
Backwards compatible for existing code, both normal Algod string tokens and previous modification that allowed dict tokens.
> Added additional header capability to algod client and it's methods

- README.md
- src/main.js
- tests/5.Transaction.js
Previous asset PRs added support for assets to class `Transaction`, but a user would have to read the code and tests to see how assets work. This PR proposes to add `make[Foo]Txn` helpers and similar to make transaction creation easier. It also proposes to update the `README.md` with usage.
https://github.com/algorand/js-algorand-sdk/issues/69
> Add wrappers to main.js - functions for making various types of txn - and usage in README.md

- src/transaction.js
- tests/7.AlgoSDK.js
The freeze state (in `Transaction`) is `omitifempty`. So, it needs to be deleted if false.
Testing: ran `it('should be able to use helper to make an asset freeze transaction'` with `freezeState=false`. It fails before this change, and passes after.
Also removed a noticed unnecessary `console.log`.
> Delete `afrz` in transaction if false

- README.md
- src/logicTemplates/htlc.js
- src/main.js
- src/transaction.js
- tests/5.Transaction.js
- tests/7.AlgoSDK.js
Add a decimals/precision field to asset creation.
Automatic unit testing. `algorand-sdk-testing` will fail due to signature mismatch, see pull 30 in "See also" section.
https://github.com/algorand/algorand-sdk-testing/pull/30
https://github.com/algorand/js-algorand-sdk/issues/96
algorand/go-algorand#601
> Add asset decimals field

- src/main.js
Add new functions in `algosdk` that expose internal functions developers need, or that accept slightly different arguments:
- `logicSigFromByte` takes encoded bytes to produce a logicsig
- `signLogicSigTransactionObject` is as `signLogicSigTransaction`, but it expects already-constructed `Transaction` rather than a dict of constructor arguments. This allows the use of groupID in combination with logicsigs.
Resolves #100 `signLogicSigTransactionObject`
Resolves #101 `logicSigFromByte`
Closes #109 out
> Extra functions in algosdk

- src/client/algod.js
- src/main.js
- src/transaction.js
- tests/5.Transaction.js
- tests/8.LogicSig.js
Class `Transaction` accepts a `params` object, and preferentially uses that to set up `lastRound` `genesisHash` et al. 
`algosdk.MakeFooTxn` helpers now have counterparts in the form of `MakeFooTxnWithParams`. `MakeFooTxn` marked `@Deprecated`, uses `params`-based implementation internally.
Add `suggestParams` function to `algod.js`, which uses `getTransactionParams` to build the `params` object that `Transaction` expects.
Unit tests pass; known broken cucumber tests fail. Because the old `MakeFoo` family of funcs calls the new `MakeFoo` family of funcs, they are tested by existing unit tests.
https://github.com/algorand/js-algorand-sdk/issues/105
> Transaction accepts params object

- src/client/algod.js
Modified `sendRawTransaction` and `sendRawTransactions` so that a `Content-Type: application/x-binary` header is set, only if the user didn't specify a Content-Type header.
This changes are backwards compatible, and address issue #116.
@ejbaran @JasonWeathersby
> Content-Type is now set when sending a transaction

- src/client/v2/indexer/lookupAccountTransactions.js
- src/client/v2/indexer/lookupAssetTransactions.js
- src/client/v2/indexer/searchAccounts.js
- src/client/v2/indexer/searchForTransactions.js
- tests/cucumber/steps/stepdefs.js
The `indexer` received an update to support rekey-related transactions. This PR proposes to likewise add support in the indexer client.
See https://github.com/algorand/algorand-sdk-testing/pull/81
> Rekey-aware indexer

- CHANGELOG.md
- src/main.js
Internal SDK tests were able to access the algodv2 and indexer clients just fine, but they weren't added to the list of module exports in `main.js`. This PR proposes to fix this.
> Hotfix/1.6.1 : add algodv2 and indexer client to module exports

- package-lock.json
- package.json
Our models use non-standard but well-supported [class fields](https://github.com/tc39/proposal-class-fields) feature but broswerify fails to handle it.
> Add babel transform for JS non-standard class fields

- src/client/client.js
- src/client/v2/algod/block.js
- src/client/v2/algod/pendingTransactionInformation.js
- src/client/v2/algod/pendingTransactions.js
- src/client/v2/algod/pendingTransactionsByAddress.js
This properly exposes msgpack responses in the browser for v2 endpoints such as `/v2/transactions/pending`.
Closes #209.
> Fix v2 msgpack endpoints for browsers

- src/client/v2/algod/block.js
- src/client/v2/algod/pendingTransactionInformation.js
- src/client/v2/algod/pendingTransactions.js
- src/client/v2/algod/pendingTransactionsByAddress.js
A small mistake prevented the original PR, #210, from actually working in browsers.
Closes #209.
> Actually fix msgpack responses

- README.md
- src/main.js
- tests/3.Address.js
Expose address encoding/decoding as `algosdk.encodeAddress` and `algosdk.decodeAddress`.
I modified existing tests to use the new public versions of these functions.
Closes #174.
> Add way to encode/decode addresses from binary

- src/main.js
- tests/7.AlgoSDK.js
It is a _very_ common use case that js user-devs wish to take a `Transaction`, convert it to bytes, and then convert it back to a `Transaction` - either for reading and writing to file, coming in as bytes from a wire, or something else. The js-sdk does support this, but usage is non-obvious and error-prone. So, this PR proposes to add three functions to `algosdk`: `unsignedTransactionToBuffer` to turn a `Transaction` into bytes, `bufferToUnsignedTransaction` to take those bytes back to a `Transaction`, and `bufferToSignedTransaction` to take the output of `Transaction.signTxn` and turn it into something more usable. (`bufferToSignedTransaction` would also work on the `blob` member of the object output by `algosdk.signTransaction`).
Added tests to ensure the output buffer is not corrupted …
> Add helpers for converting buffers to Transactions and vice versa.

- src/main.js
- tests/5.Transaction.js
All make transaction functions now take in an optional `rekeyTo` parameter.
Closes #207
> Add rekey param to make txn functions

- package-lock.json
- package.json
- src/encoding/encoding.js
- tests/2.Encoding.js
See #130. This PR proposes to change the js-sdk to use a fork that supports `BigInt`<->`uint64` encode/decode. 
Resolves #130
> Use msgpack fork that supports bigints. 

- .travis.yml
- src/client/client.js
- src/client/v2/algod/models/base.js
- src/transaction.js
- tests/cucumber/browser/test.js
- tests/cucumber/docker/Dockerfile
- tests/cucumber/steps/index.js
- tests/cucumber/steps/steps.js
- tests/mocha.js
* Switched to an Ubuntu base image for the docker test runner since installing Firefox on Debian proved to be more difficult.
* Firefox tests were failing because of the issue I pointed out here: https://github.com/mozilla/geckodriver/issues/1798. I implemented a workaround to this by using the helper functions `makeUint8Array` and `makeEmptyObject` and by fixing how we check for arrays in the SDK.
* I also found that the code for POST and DELETE requests throw a `Response` object instead of an `Error` if an error occurs, so I fixed this to improve the error message that gets displayed.
> Fix firefox tests

- src/client/v2/algod/sendRawTransaction.js
- src/logicsig.js
- src/main.js
Closes #153, closes #220, closes #222
> Fixes for community tickets

- src/group.js
- tests/5.Transaction.js
> assignGroupID handles mixed txn-dict and txn-obj

- src/transaction.js
- tests/5.Transaction.js
If you have a built `Transaction`, then calling `console.log(theTxn)` does not give very useful information. Addresses are formatted for bytes, for example. This PR proposes to add a `prettyPrint()` function on class `Transaction` for user-dev debug.
I am especially looking for feedback on what fields should be edited and how. Currently the focus is on returning addresses to string, the genesis hash displays as b64, and the tag is returned to normal.
Added a minimal unit test that checks if pretty print throws.
Closes #240
> Pretty Print function for Transaction

- src/makeTxn.js
- src/transaction.js
- tests/5.Transaction.js
Currently, the Javascript SDK does not validate `assetMetadataHash` properly. This value is supposed to be exactly 32 bytes long, but if you pass in a smaller value the Javascript SDK will construct and sign a transaction with that smaller value.
Then when the transaction reaches the server, the `assetMetadataHash` gets unpacked into [the field here](https://github.com/algorand/go-algorand/blob/1424855ad2b5f6755ff3feba7e419ee06f2493da/data/basics/userBalance.go#L354), which is 32 bytes long. In the case of a smaller value, it appears extra 0s are added. This means that when the server tries to verify the transaction signature it fails because a different transaction with a shorter `assetMetadataHash` was actually signed in Javascript.
This PR fixes this by throwing an error if …
> Validate that assetMetaDataHash is 32 bytes

- src/multisig.js
The `mergeMultisigTransactions` function currently does not work when used in a React app because it calls `Buffer.compare` with Uint8Array arguments. The latest version of the `buffer` package supports this, but unfortunately [react-scripts](https://www.npmjs.com/package/react-scripts) v4.0.1 uses an older version of webpack to build apps, which overrides the `buffer` package with an older version that does not support comparing Uint8Arrays.
This PR converts the Uint8Array arguments to Buffers before calling `Buffer.compare` to fix this issue.
When react-scripts updates to webpack v5 (tracked by [this issue](https://github.com/facebook/create-react-app/issues/9994)), it should stop overriding the `buffer` module and this change can be reverted.
Fixes #252.
> Fix React multisig error

- src/transaction.js
- tests/5.Transaction.js
Currently's it's not possible to construct an asset creation transaction that has a total issuance larger than 2^53-1, or transfer asset amounts that exceed 2^53-1. This PR fixes this by allowing the Transaction constructor to accept BigInts for the asset total parameter and amount parameter. Since our msgpack fork already supports encoding and decoding BigInts, this just updates the gatekeeping logic we perform on `amount` and `assetTotal`.
> Allow BigInts to be used in Transaction constructor

- src/makeTxn.js
- src/transaction.js
- tests/5.Transaction.js
The current implementation of these functions initializes the object with the field rekeyTo  (lowercase letter K) causing the build of the rekey transaction to fail because the expected field name is reKeyTo (uppercase letter K).
- makePaymentTxnWithSuggestedParams
- makeKeyRegistrationTxnWithSuggestedParams
- makeAssetCreateTxnWithSuggestedParams
- makeAssetConfigTxnWithSuggestedParams
- makeAssetDestroyTxnWithSuggestedParams
- makeAssetFreezeTxnWithSuggestedParams
- makeAssetTransferTxnWithSuggestedParams
To avoid this problem in the future, reKeyTo has been changed by rekeyTo in src/makeTxn.js and src/transaction.js (As it is in the node go-algorand)
> Fixing rekeyTo makeTxnWithSuggestedParams bug

- README.md
- src/encoding/address.js
- tests/3.Address.js
Fixed also an npm command in readme
Fixes #262
> decodeAddress now verifies the checksum (fixes #262)

- src/transaction.js
- tests/5.Transaction.js
Improve the handling of arrays in the `Transaction` constructor:
* Input arrays (specifically `appAccounts`) are no longer modified.
* All arrays are copied (using `map` or `slice`) to avoid modification by the caller after creation.
* Additional type checking was added to verify arguments are arrays.
Fixes #273.
> Fix Transaction constructor handling of arrays

- src/logicsig.js
- tests/8.LogicSig.js
Currently if you attempt to use the `signLogicSigTransaction` function to make a LogicSig contract account sign a transaction whose sender is not the LogicSig's computed address, an error will be thrown. This means that sending transactions form an account rekeyed to a LogicSig is not possible.
This PR fixes this issue by allowing non-delegated LogicSigs to sign transactions from any address, adding in the AuthAddr field to the signed transaction if necessary.
> Allow LogicSigs to sign txns with a different AuthAddr

- package-lock.json
- package.json
- src/client/client.js
- src/client/v2/algod/accountInformation.js
- src/client/v2/algod/algod.js
- src/client/v2/algod/compile.js
- src/client/v2/algod/getApplicationByID.js
- src/client/v2/algod/getAssetByID.js
- src/client/v2/algod/status.js
- src/client/v2/algod/statusAfterBlock.js
- src/client/v2/algod/supply.js
- src/client/v2/indexer/indexer.js
- src/client/v2/indexer/lookupAccountByID.js
- src/client/v2/indexer/lookupAccountTransactions.js
- src/client/v2/indexer/lookupApplications.js
- src/client/v2/indexer/lookupAssetBalances.js
- src/client/v2/indexer/lookupAssetByID.js
- src/client/v2/indexer/lookupAssetTransactions.js
- src/client/v2/indexer/lookupBlock.js
- src/client/v2/indexer/makeHealthCheck.js
- src/client/v2/indexer/searchAccounts.js
- src/client/v2/indexer/searchForApplications.js
- src/client/v2/indexer/searchForAssets.js
- src/client/v2/indexer/searchForTransactions.js
- src/client/v2/jsonrequest.js
- src/utils/utils.js
- tests/2.Encoding.js
- tests/cucumber/steps/steps.js
Several of the aglod REST APIs can return JSON responses with integer values greater than JavaScript's maximum safe integer value. To fix this problem, this PR uses the [json-bigint](https://www.npmjs.com/package/json-bigint) library to parse the JSON response from our endpoints. This PR introduces the following modes to parse integers:
* `"default"`: Integers will be decoded according to `JSON.parse`, meaning they will all be Numbers and any values greater than `Number.MAX_SAFE_INTEGER` will lose precision.
* `"safe"`: All integers will be decoded as Numbers, but if any values are greater than `Number.MAX_SAFE_INTEGER` an error will be thrown.
* `"mixed"`: Integers will be decoded as Numbers if they are less than or equal to `Number.MAX_SAFE_INTEGER`, otherwise they will be decoded as …
> Support for decoding BigInts

- src/encoding/uint64.js
- src/main.js
- tests/2.Encoding.js
Add the following helper functions to the SDK:
* `encodeUint64` takes a number or BigInt and encodes it into an 8-byte big-endian byte array.
* `decodeUint64` takes a byte array and decodes it back into a number or BigInt.
The return type (number or BigInt) of `decodeUint64` is based on the optional parameter `decodingMode`. The possible values are:
* `"safe"` (default): The integer will be decoded as a Number, but if it is greater than `Number.MAX_SAFE_INTEGER` an error will be thrown.
* `"mixed"`: The integer will be decoded as a Number if it is less than or equal to `Number.MAX_SAFE_INTEGER`, otherwise it will be decoded as a BigInt.
* `"bigint"`: The integer will always be decoded as a BigInt.
These values align with the int decoding options for API responses introduced in #260. …
> Add encodeUint64 and decodeUint64 helper functions

- src/logicsig.js
- tests/8.LogicSig.js
Fixes #287 by allowing the `signLogicSigTransaction` function to accept Transaction objects as opposed to JS objects.
> Allow `signLogicSigTransaction` to accept Transaction objects

- src/convert.js
- src/encoding/address.js
- src/main.js
- src/mnemonic/mnemonic.js
- src/multisig.js
- tests/1.Mnemonics_test.js
- tests/3.Address.js
Fixes #286 by setting error *messages* instead of initialized Error instances. This allows for error traces to be more informative to the user. Please refer to #286 for additional details.
> Initialize errors when they occur for improved error traces

- Makefile
- src/client/v2/algod/algod.js
- src/client/v2/algod/genesis.js
- src/client/v2/algod/proof.js
- src/client/v2/indexer/indexer.js
- src/client/v2/indexer/lookupAccountByID.js
- src/client/v2/indexer/lookupApplications.js
- src/client/v2/indexer/lookupAssetBalances.js
- src/client/v2/indexer/lookupAssetByID.js
- src/client/v2/indexer/lookupTransactionByID.js
- src/client/v2/indexer/searchAccounts.js
- src/client/v2/indexer/searchForApplications.js
- src/client/v2/indexer/searchForAssets.js
- tests/cucumber/browser/test.js
- tests/cucumber/steps/steps.js
Add support for the new `include-all` query param on some indexer endpoints, and add support for relevant cucumber tests.
Also, I removed the `round` query param from the request builders for `/v2/applications` and `/v2/applications/<app-id>` since this param does not apply to those endpoints.
Closes #282.
> Support new features from indexer 2.3.2

- src/logic/langspec.json
- src/logic/logic.js
- tests/8.LogicSig.js
Update the TEAL langspec file for v3 and add support for parsing constants from `pushint` & `pushbytes`.
Closes #288.
> Add TEAL 3 support

- src/account.ts
- src/convert.ts
- src/group.ts
- src/main.ts
- src/transaction.ts
- src/types/account.d.ts
Closes #310. Also adds `TransactionLike` type and `instantiateTxnIfNeeded` utility method.
> Migrate convert, group, account files to TypeScript

- src/logic/logic.ts
- tsconfig.json
> Migrate `logic.js` to TypeScript

- README.md
- examples/README.md
> Add disclaimer to `examples/README.md` about when the `ts-node` package is required

- src/bid.ts
- src/logic/logic.ts
- src/logicsig.ts
- src/main.ts
- src/multisig.ts
- src/types/transactions/encoded.ts
- tests/7.AlgoSDK.js
- tests/8.LogicSig.js
This PR migrates `logicsig.js`, `bid.js`, and `multisig.js` to TypeScript, including new type definitions as needed. Closes #306.
> Migrate LogicSig, Bid, and Multisig to TypeScript

- src/transaction.ts
- tests/5.Transaction.js
This PR fixes an encoding inconsistency between this SDK and algod when `lease` or `assetMetadataHash` consist of all zeros. A similar fix for the Python SDK was recently merged: algorand/py-algorand-sdk#174.
Fixes #272.
> Fix encoding of all 0 lease and assetMetadataHash

- .vscode/settings.json
- src/client/client.ts
- src/client/v2/algod/suggestedParams.ts
- src/client/v2/jsonrequest.ts
- src/group.ts
- src/main.ts
- src/makeTxn.ts
- tests/9.Client.ts
* Remove deprecated ESLint setting
* Specify `SuggestedParams` type for the SuggestedParams client request
* Fix default generic types of the `JSONRequest` class
* Provide better return type for the `assignGroupID` method
* Export `Account` type
Closes #336.
> Final TypeScript changes

- src/client/v2/algod/algod.ts
- src/client/v2/algod/compile.ts
This small change allows `Uint8Arrays` to be passed into the algod `compile` method.
> Allow byte arrays in algod compile

- FAQ.md
- README.md
* Move `dist` directory disclaimer from the build section of the README to an FAQ file.
Closes #341.
> Include link to `dist` directory in the README’s installation section

- webpack.config.js
> Use `UMD` library type instead of `window` so React environments can also use the browser bundle

- src/types/transactions/base.ts
This PR fixes fields such as  `assetManager` and `assetClawback` in the `TransactionParams` type that are incorrectly marked as required.
Closes #358.
> Fix asset creation transaction types that should be optional

- src/client/v2/algod/dryrun.ts
This change addresses Issue algorand#366, which points out that the constructor for the `Dryrun` class should be of type `DryrunRequest`, instead of `DryrunSource`.
> Use DryrunRequest instead of DryrunSource in constructor

- examples/asset_accept_example.js
- examples/asset_create_example.js
- examples/asset_destroy_example.js
- examples/asset_freeze_example.js
- examples/asset_revoke_example.js
- examples/asset_send_example.js
- examples/asset_update_example.js
Show how to let the SDK fetch suggested parameters as an alternative to setting them manually.
> Update examples on getting `suggestedParams`

- src/encoding/uint64.ts
- src/transaction.ts
Hey guys! I'm part of Rand Labs team and we are creating an algo-wallet for React Native.
The sdk works well on iOS but on Android throws the next error:
Doing a debug, this is because of the way of comparing a big int directly with hexadecimal
I make a quick fix on this PR jus casting the hexadecimal to a BigInt
> Fix: Cast hexadecimal literals to BigInt to be compatible with React Native applications on android

- .eslintrc.js
- src/client/client.ts
- src/encoding/uint64.ts
- src/makeTxn.ts
- src/multisig.ts
- src/transaction.ts
- tests/5.Transaction.js
- tests/6.Multisig.js
- tests/cucumber/steps/steps.js
This PR fixes a bug that incorrectly prohibited encoding a transaction with a first round of zero. When using the new devMode flag, rounds are incremented by transactions instead of the flow of time and so it is often the case that the last round (and therefore the first valid round) received from the transaction params endpoint is 0.
To support that use case, this PR adds the first valid round property to the list of transaction properties that are allowed to be zero.
> Support transactions with a first round of zero

- package.json
This PR adds a `prepare` script to the `package.json` to support npm installing this repository with the git URL like so:
```sh
$ npm install --save https://github.com/algorand/js-algorand-sdk
```
The above command worked previously when the `dist` directory was stored in version control but, since it has been removed, the convention [starting in NPM v4](https://stackoverflow.com/questions/48287776/automatically-build-npm-module-on-install-from-github/57503862#57503862) is to add any necessary build scripts to the `prepare` script in `package.json`, so that npm knows how to build your cloned repository.
> Add `prepare` script to support npm installing with the git URL

- src/client/v2/algod/dryrun.ts
- src/client/v2/algod/models/base.ts
- src/client/v2/algod/models/types.ts
- templates/model.vm
- tests/7.AlgoSDK.js
This fixes an issue where the `ApplicationParams` dryrun model object expects programs to be base64 strings, but these programs were not properly encoded to msgpack for use with algod's dryrun endpoint.
Now, programs can be passed as `Uint8Array`s or base64 strings. Internally any base64 strings will be decoded to `Uint8Array`s.
I've added an argument to `BaseModel.get_obj_for_encoding` called `binary`, which indicates whether raw binary objects (`Uint8Array`s) are acceptable or if they should be encoded as base64 strings.
Fixes algorand/go-algorand#2495, fixes #373.
> Fix msgpack encoding of dryrun objects

- src/transaction.ts
- tests/5.Transaction.js
`Transaction.from_obj_for_encoding` currently ignores the extra pages field, `apep`, from the encoded transaction, meaning this information is lost during decoding.
Closes #418.
> Properly decode transaction extra pages field

- src/transaction.ts
- tests/5.Transaction.js
This PR extends
https://github.com/algorand/js-algorand-sdk/pull/450
adding support for offline key registration transactions too.
Previously offline key registration would not be deserializable.
> Support deserializing nonpart and offline keyreg

- FAQ.md
- README.md
* SRI (subresource integrity) ensures that the CDN cannot serve a
malicious script. This is quite important for the Algorand SDK
as the Algorand SDK can be used in quite sensitive websites.
See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
* Use the full URL for algosdk.min.js in the CDN so that the
source map is properly found by the browser which facilitates
debugging
* Close the `<script>` tag using `</script>` for better compatibility
* Specify explicitely the cross-origin to be `anonymous`
> Add SRI for security and misc changes for browser

- src/makeTxn.ts
Fix a small type bug in the `makeApplicationOptInTxn` function.
Closes #470
> Fix `foreignAssets` type

- .eslintrc.js
- Makefile
- src/abi/abi_type.ts
- src/abi/contract.ts
- src/abi/index.ts
- src/abi/interface.ts
- src/abi/method.ts
- src/composer.ts
- src/logicsig.ts
- src/main.ts
- src/makeTxn.ts
- src/multisig.ts
- src/signer.ts
- src/types/intDecoding.ts
- src/types/transactions/base.ts
- tests/cucumber/browser/test.js
- tests/cucumber/steps/index.js
- tests/cucumber/steps/steps.js
> Add ABI interaction support

- .eslintrc.js
- CHANGELOG.md
- FAQ.md
- Makefile
- README.md
- package-lock.json
- package.json
- src/abi/abi_type.ts
- src/abi/contract.ts
- src/abi/index.ts
- src/abi/interface.ts
- src/abi/method.ts
- src/client/v2/algod/models/types.ts
- src/composer.ts
- src/encoding/bigint.ts
- src/logicsig.ts
- src/main.ts
- src/makeTxn.ts
- src/multisig.ts
- src/signer.ts
- src/transaction.ts
- src/types/intDecoding.ts
- src/types/transactions/base.ts
- src/wait.ts
- tests/10.ABI.ts
- tests/5.Transaction.js
- tests/cucumber/browser/test.js
- tests/cucumber/steps/index.js
- tests/cucumber/steps/steps.js
- ABI Support for JS library (#454)
- ABI interaction support (#466)
- Wait for confirmation function (#469)
- Add freezeAccount encoding in display method (#460)
- Regenerate code from specification file (#456)
- Fix type for foreignAssets (#472)
> DO NOT MERGE - js-algorand-sdk v1.13.0 beta.1

- package-lock.json
- package.json
- typedoc.config.json
[TypeStrong/typedoc #1739: Warning states Object is defined and referenced, but not included in the documentation. Why?](https://github.com/TypeStrong/typedoc/issues/1739)
[TypeString/typedoc #1657: Generate documentation also for indirect exported Types.](https://github.com/TypeStrong/typedoc/issues/1657)
[TypeStrong/typedoc #1521: Default exports should retain their name](https://github.com/TypeStrong/typedoc/issues/1521)
Closes #461
> Export sdk subclasses to typedoc

- .gitignore
- src/client/baseHTTPClient.ts
- src/client/client.ts
- src/client/kmd.ts
- src/client/urlTokenBaseHTTPClient.ts
- src/client/v2/algod/algod.ts
- src/client/v2/indexer/indexer.ts
- src/client/v2/serviceClient.ts
- src/main.ts
- tests/9.Client.ts
Currently the only way for a dApp to use the SDK with an API service is to know the URL and token of the API service.
This prevents dApps from using API services / algod / indexer provided by the user or by a wallet such as AlgoSigner.
In particular:
* When using a wallet such as AlgoSigner, a dApp either need to manually serialize data and write path for endpoints (https://github.com/PureStake/algosigner/blob/develop/docs/dApp-integration.md#algosigneralgod-ledger-mainnettestnet-path-algod-v2-path--) or need to not use at all the provided API service.
* A user cannot use their preferred (potentially more trusted) API service / algod / index / API services
* A dApp cannot easily connect to a private network of the user
(See also https://github.com/algorandfoundation/ARCs/pull/8 for more …
> Enabling a custom client for Algod and Indexer

- src/wait.ts
Fixes the following issue with the wait for confirmation function:
1. If the call to `pendingTransactionInformation` throws an error, that error should be ignored and the function should continue retrying if `waitRounds` allows it.
> Fix wait for confirmation function

- src/client/urlTokenBaseHTTPClient.ts
- tests/cucumber/steps/steps.js
Improve the HTTP error messages that superagent returns.
Before this PR, an error would look like:
```
Error: Bad Request
```
After this PR, it contains the error message returned from the server, like this:
```
Error: Network request unsuccessful. Received status 400: TransactionPool.Remember: transaction QJALLV5B3QDLCOOMOBGBEORNUGBRNNG6DVQ2DN42XATI4P2WFSAA: logic eval error: + overflowed. Details: pc=316, opcodes=load 4
btoi
+
```
Closes #462
> Improve HTTP error messages

- src/abi/abi_type.ts
- src/abi/contract.ts
- src/abi/index.ts
- src/abi/interface.ts
- src/abi/method.ts
- src/abi/reference.ts
- src/abi/transaction.ts
- src/composer.ts
- src/transaction.ts
- tests/cucumber/docker/run_docker.sh
- tests/cucumber/steps/steps.js
> Support ABI reference types and other improvements

- src/client/v2/algod/algod.ts
- src/client/v2/serviceClient.ts
I was looking at this repo's source code and cross-checking with the REST APIs doc and got super annoyed....
**Live Deployment**
https://js-algosdk.netlify.app/classes/algodv2
> Document Algodv2 methods

- src/client/v2/indexer/indexer.ts
- src/client/v2/indexer/lookupAssetBalances.ts
I'd really like to document each indexer endpoint's class given the number of queries available.
However that will take quite some time and will make it harder for the reviewer to go through.... so let's start with the Indexer page and just `LookupAssetBalances` for now.
https://indexer-doc--js-algosdk.netlify.app/classes/indexer
https://indexer-doc--js-algosdk.netlify.app/classes/_internal_.lookupassetbalances
> Document Indexer methods

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/client/v2/algod/algod.ts
- src/client/v2/indexer/indexer.ts
- src/client/v2/indexer/lookupAssetBalances.ts
- src/client/v2/serviceClient.ts
- src/dryrun.ts
- src/main.ts
- Create dryrun (#478)
- Support ABI reference types and other improvements (#482)
- Improve HTTP error messages (#485)
- Enabling a custom client for Algod and Indexer (#477)
- Export sdk subclasses to typedoc (#479)
- ABI Support for JS library (#454)
- ABI interaction support (#466)
- Wait for confirmation function (#469)
- Add freezeAccount encoding in display method (#460)
- Regenerate code from specification file (#456)
- Document Indexer methods (#491)
- Document Algodv2 methods (#486)
- Update chromedriver (#492)
- Fix wait for confirmation function (#480)
- Fix type for foreignAssets (#472)
> FOR REVIEW ONLY - js-algorand-sdk v1.13.0

- src/client/client.ts
- tests/9.Client.ts
Hey team,
I think I found a bug in how we decode json responses; essentially, we always pick the wrong parser.
Look at the following code snippet:
```typescript
const assetDetails = await client
.getAssetByID(ASAIdx)
.setIntDecoding(algosdk.IntDecoding.BIGINT)
.do();
console.log(typeof assetDetails.params.total);
```
Before: `number`
Now: `bigint`
I also think that we should add a unit test for this. My JS skills are somehow limited, but I'd be happy to give it a shot if you point me in the right direction :)
> Fix JSON decoding

- FAQ.md
- README.md
Developers on webpack 5 or vite often face errors when they first installed the sdk.
I think adding some instructions on the README would be helpful.
> Add installation instructions for vite users

- src/logic/langspec.json
- tests/8.LogicSig.ts
This PR updates the JS SDK langspecs for TEAL 6 and adds some sanity checks to make sure v6 programs are able to be compiled.  
Closes #503
> Update langspec for TEAL 6

- src/makeTxn.ts
- src/types/utils.ts
Currently, the IntelliSense for `FromObject` transaction functions are not human readable:
This PR adds an Expand type that expands these types for IntelliSense:
As confirmed by the mocha tests, functionality is preserved, this is merely a change for improved IntelliSense.
> Make FromObject parameter IntelliSense human readable

- src/client/client.ts
Revert the behavior change in #477 which caused our HTTP client to determine the type (i.e. JSON or not) of a response based on the response headers. In theory this is an ok thing to do, but some edge cases have been reported where the response headers have been incorrect or not present -- in any case, they are not the most reliable.
This PR reverts HTTP response handing to our old behavior, which is to use the `format` query param to determine the response format for GET requests. POST and DELETE requests assume the response is always JSON (we don't have any endpoints that go against this assumption).
Closes #526
> Use HTTP request format arg to determine response type

- tests/cucumber/steps/steps.js
There was a [PR in the SDK testing repo](https://github.com/algorand/algorand-sdk-testing/pull/162) that changed the wording for one of the cucumber steps. This PR makes sure that the JS steps conform to this wording change.
> Fix cucumber tests for asset lookup step

- src/dryrun.ts
This PR fixes #538 
The error stems from line 84, which checks if the appIndex is zero:
```js
if (t.txn.appIndex === 0) {
```
When creating a new transaction, `t.txn.appIndex` will be `undefined` instead of zero. To get intended functionality, we must be checking if `t.txn.appIndex` is `undefined`, otherwise it will assume the created app is a pre-exsting app and attempt to pass `undefined` as the appIndex.
> fix app creation createDryrun error

- .github/workflows/codegen.yml
Adds a github workflow which will call our code gen action.  
Depends on action being defined in  our generator... See https://github.com/algorand/generator/pull/32 for more details and testing done.
Runs on a cron job daily at 23:20. The Github docs say to try to avoid common times because there will be natural spikes of event processing happening then, so I've defined all of the jobs at an arbitrary time during the night.
It will run the code generator, commit to a branch if necessary, and open a PR for us to review. It will no-op if the branch w/ identical changes already exist.
> Build: Add SDK code generation workflow

- src/client/v2/algod/models/types.ts
Depends on: https://github.com/algorand/go-algorand/pull/3957
> Generate updated client API code

- src/utils/utils.ts
- tests/2.Encoding.js
This PR fixes a couple of bugs with safe mode for integer decoding during json parse:
- safe mode threw errors if `10**15 > value < Number.MAX_SAFE_INTEGER `. It would have shown in the unit test if we had tested for edge cases.
- safe mode did not decode integers as numbers. It didn't alter the output of JSONbig in any way.
It is again only an issue for those values that are `10**15 > value < Number.MAX_SAFE_INTEGER `
> fix: safe intDecoding

- FAQ.md
- package-lock.json
- package.json
- src/client/urlTokenBaseHTTPClient.ts
- webpack.config.js
With the removal of the dependency to node's path module, there's one less thing to 'browserify'. All tests, especially the ones under client url construction, passed. I'll leave the the webpack configuration updates to you all, I guess...
> Remove code that relies on node's path module

- src/client/v2/algod/algod.ts
- src/client/v2/algod/getApplicationBoxes.ts
- src/client/v2/algod/models/types.ts
- tests/cucumber/docker/run_docker.sh
- tests/cucumber/steps/steps.js
This PR adds the GetApplicationBoxes API endpoint in the v2 `algod` client and adds cucumber integration tests.
> Box Storage: Add GetApplicationBoxes API and cucumber steps 

- tests/8.LogicSig.ts
This PR adds additional version consolidation changes to the [existing TEAL/AVM language consolidation PR](https://github.com/algorand/js-algorand-sdk/pull/609).
> LogicSig test names version consolidation

- src/main.ts
- src/multisig.ts
- src/nacl/naclWrappers.ts
- src/transaction.ts
- tests/4.Utils.ts
- tests/6.Multisig.ts
- tests/7.AlgoSDK.js
This PR adds an `attachSignature` method to the Transaction class and related external signature methods for multisig transactions.
> API: Support attaching signatures to standard and multisig transactions

- tests/cucumber/steps/steps.js
Extends #614 to add `await` to `waitForAlgodInDevMode` invocations.  Webstorm IDE warnings pointed out the async call is missing `await`.
Additionally, the PR reverts interactions in _the transaction should go through_ to mirror prior to #614.  I think the shuffling in #614 is not necessary.
> Add missing await for async function calls

- tests/cucumber/steps/steps.js
Extends #614 to remove what appears to be unnecessary v2 algod client usage.  The initialization of a v2 client in _an algod client_ led me to creating the PR.
Note - Predating the PR, there is a flaky test:  _Scenario: Getting transaction by ID_.  The PR does not attempt to remedy it.
> Remove unnecessary use of v2 algod client

- Makefile
- tests/cucumber/docker/run_docker.sh
- tests/cucumber/steps/steps.js
This PR aims to allow Dev mode network to be used in cucumber tests to speed up testing time. 
Cucumber's `this` and `World` objects seem to be bound to the steps, so I refrained from using helper methods that rely on state associated with the cucumber's world/this object. This PR also removes some `statusAfterBlock` v1 API calls, as they seem to be more flaky in dev mode, and often a redundant step in the scheme of the entire cucumber scenario.
> Testing: Use Dev mode network for cucumber tests

- Makefile
- tests/cucumber/steps/steps.js
* `we make a Pending Transaction Information against txid {string} with max {int}`
* `we make a Lookup Asset Balances call against asset index {int} with limit {int} nextToken {string} currencyGreaterThan {int} currencyLessThan {int}`
* `we make a Lookup Asset Transactions call against asset index {int} with NotePrefix {string} TxType {string} SigType {string} txid {string} round {int} minRound {int} maxRound {int} limit {int} beforeTime {int} afterTime {int} currencyGreaterThan {int} currencyLessThan {int} address {string} addressRole {string} ExcluseCloseTo {string}`
* `we make a LookupApplications call with {int} and {int}`
* `we make a Search Accounts call with assetID {int} limit {int} currencyGreaterThan {int} currencyLessThan {int} and nextToken {string}`
* `we make a Search For …
> Command to generate input for Unused Steps Analysis Script + Remove those steps

- test-harness.sh
Following up from the companion [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224), we're going to pass through verbosity to the harness script via a new `-v` flag.
For further context: here is what [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224) says:
> The sandbox is always defaulting to `release` and the generated `config.harness` isn't sticking because the verbose flag is provided in the wrong order. 
> 
> Additionally, after refactoring the SDK Sandboxization PR's to no longer overwrite `.env`, there is no way to pass through the verbosity, except by overwriting. The PR re-enables passing through by also reading `VERBOSE_HARNESS` as a flag (either `-v` or `--verbose`).
> Bug-Fix: Pass verbosity to the harness and sandbox

- .gitignore
Adds a `.gitignore` entry for directory created by algorand-sdk-testing:  `test-harness/` matching the convention in other SDKs.
> Tidy:  Ignore algorand-sdk-testing test-harness dir

- tests/cucumber/steps/steps.js
1.  **When**: `I create the payment transaction`
2. **Given**: `'key registration transaction parameters {int} {int} {int} {string} {string} {string} {int} {int} {int} {string} {string}'`
3. **When**: `I create the key registration transaction`
> Enhancement: Removing more unused steps

- src/client/algod.js
This PR adds the deprecated tag in the JSDoc to the algod v1 client. The older transaction format has already been marked with the deprecated tag in a previous PR in `makeTxn.ts`.
After "sunsetting" the deprecated code in `algod.js` and `makeTxn.ts`, any unit tests and cucumber steps that use them should be deleted as well.
> Enhancement: Add deprecation tag to algod v1 client

- .test-env
- Makefile
- src/client/v2/algod/algod.ts
- src/client/v2/algod/getBlockHash.ts
- src/client/v2/indexer/lookupBlock.ts
- test-harness.sh
- tests/cucumber/steps/steps.js
- tests/cucumber/unit.tags
REST API changes and test implementations.
Tests are passing locally, CI is pending https://github.com/algorand/algorand-sdk-testing/pull/245
> REST API: Add algod block hash endpoint, add indexer block header-only param.

- src/client/v2/algod/algod.ts
I found another typo in your docs😂. I tested that it's not overloaded throwing this error `Invalid format for parameter application-id: error binding string parameter: strconv.ParseUint: parsing "undefined": invalid syntax`
> API: Fix docs typo

- .circleci/config.yml
- .npmrc
- package.json
- tests/cucumber/docker/Dockerfile
Upgrades node.js from v12 to v14 for several reasons:
* Per https://endoflife.date/nodejs, v14 is the oldest actively supported version.  v12 is EOL.
* https://github.com/giggio/node-chromedriver no longer supports < v14 as evidenced by the following failed build:   https://app.circleci.com/pipelines/github/algorand/js-algorand-sdk/689/workflows/c78c8140-c32d-4706-abee-f0ec8f88b837/jobs/3993.  A quick scan shows the project no longer builds against v12:  https://github.com/giggio/node-chromedriver/commit/ebe7524dcf334a7277a1ac2aed7a6f59389a5b0f.
> CI:  Upgrade node.js from v12 to v14

- package-lock.json
- package.json
This PR does two things:
* Update `package-lock.json` with the `engines` property introduced by #680
* Remove the `fsevents` optional dependency unintentionally introduced in #590
> CI: Remove unneeded dependency & update package-lock

- CHANGELOG.md
- package-lock.json
- package.json
* fix: mergeMultisigTransactions logic error by @AlgoDoggo in https://github.com/algorand/js-algorand-sdk/pull/675
* CI: Remove unneeded dependency & update package-lock by @jasonpaulos in https://github.com/algorand/js-algorand-sdk/pull/684
* Boxes: Add support for Boxes by @algochoi in https://github.com/algorand/js-algorand-sdk/pull/604
* Enhancement: Code generation improvements by @jasonpaulos in https://github.com/algorand/js-algorand-sdk/pull/663
* Network: Replace `superagent` with `fetch` for HTTP requests by @jasonpaulos in https://github.com/algorand/js-algorand-sdk/pull/676
* API: Fix docs typo by @PabloLION in https://github.com/algorand/js-algorand-sdk/pull/677
* CI:  Upgrade node.js from v12 to v14 by @michaeldiamant in https://github.com/algorand/js-algorand-sdk/pull/680
* …
> FOR REVIEW ONLY - Release v1.23.1

- src/client/v2/algod/models/types.ts
Adds NodeStatusResponse fields mirroring https://github.com/algorand/go-algorand/pull/4808.
> REST API:  Add KV counts to NodeStatusResponse

- src/multisig.ts
I didn't see this function in the docs, is it because the name doesn't match?
> Fix: createMultisigTransaction name in comments

- .test-env
- src/abi/abi_type.ts
- tests/10.ABI.ts
Fixes https://github.com/algorand/js-algorand-sdk/issues/497
> Enhancement: allowing zero-length static array

- src/logicsig.ts
Adds LogicSig usage disclaimer suggesting LogicSigAccount usage as a more general purpose signing mechanism.
> Add LogicSig usage disclaimer

- CHANGELOG.md
- src/client/v2/algod/models/types.ts
- src/dryrun.ts
- tests/7.AlgoSDK.js
- tests/cucumber/steps/steps.js
This PR changes the generated constructors so that every constructor accepts an object instead of explicit arguments. Previously, this was only done for methods with greater than 4 arguments. 
Also deletes some stale types that have been since marked as `private` in the API spec.
Changes that stem from generator change: https://github.com/algorand/generator/pull/52/files
> v2: Regenerate models

- src/composer.ts
- tests/10.ABI.ts
This PR adds foreign array objects as arguments in `addMethodCall()` for the atomic transaction composer.
Adds a test that mirrors the Go SDK: https://github.com/algorand/go-algorand-sdk/pull/318. Currently written as a unit test, but could also benefit from a cucumber test since all the other SDKs implement this. 
Addresses #653
> Enhancement: Add foreign array objects to ATC `addMethodCall`

- src/logicsig.ts
- src/main.ts
- tests/7.AlgoSDK.js
Introduce a new function `verifyTealSign` which can be used to verify the output of its pair method, `tealSign`.
Some applications might benefit from having this utility function, either for testing purposes or not, and it would save developers the work of importing the `nacl` library and doing the verification manually by themselves.
> API: verifyTealSign utility function

- .test-env
- src/client/v2/algod/algod.ts
- src/client/v2/algod/models/types.ts
- src/client/v2/algod/simulateTransaction.ts
- src/composer.ts
- src/encoding/encoding.ts
- src/signer.ts
- src/transaction.ts
- tests/cucumber/integration.tags
- tests/cucumber/steps/steps.js
This PR:
* Generates Simulate-related objects/types
* Adds algod support for the simulate endpoint
* Implements cucumber tests from this [SDK testing PR](https://github.com/algorand/algorand-sdk-testing/pull/265)
To support sending unsigned transactions to the simulate endpoint, also adds `encodeNoSigTransaction()` to encode them. Currently, algod does not seem to decode `Transaction`, so we wrap them in a `SignedTransaction`-like object, but set the sig field to null. For simulating unsigned txns in the ATC, added `makeNoSigTransactionSigner` to allow the transaction signer to encode unsigned transactions and simulate them.
TODO:
* SDK Tests need to be merged in first
* Need to fix CI tests due to some issues with indexer in dev mode (local tests pass for the new `@simulate` tag)
> algod: Simulate Endpoint

- src/client/v2/algod/simulateTransaction.ts
- src/composer.ts
- tests/cucumber/steps/steps.js
This PR makes some minor, but important changes to the simulate support introduced in #743. They are:
1. `SimulateRawTransactions` was returning a raw object instead of an instance of `SimulateResponse`. Based on the code I think we wanted a `SimulateResponse`
2. An operation which can error was moved outside of a try-catch block in `AtomicTransactionComposer.execute`. I made a new try-catch block to include it again. This is especially important because it can be dangerous if a client thinks a transaction was rejected due to an error observing its result, but in reality the transaction succeeded.
> algod: Minor improvements to simulation support

- src/makeTxn.ts
> Fix: allow nonParticipation flag to be a boolean

- .test-env
- src/client/v2/algod/algod.ts
- src/client/v2/algod/models/types.ts
- src/client/v2/algod/simulateTransaction.ts
- src/transaction.ts
- tests/cucumber/steps/steps.js
Support the changes to simulate from https://github.com/algorand/go-algorand/pull/5292
> API: Support updated simulate endpoint

- .circleci/config.yml
- package-lock.json
- package.json
- tests/cucumber/docker/Dockerfile
Updates node version minimum and in circle CI to avoid relying on a deprecated version.
Also ran `npm audit fix` to update dependencies in order to get fixes for vulnerabilities in our dependency packages.
> node: Drop support for node v14, npm audit fix

- src/main.ts
Exports token header types for all of the existing clients.
Resolves #437
> client: Export token header types

- FAQ.md
- README.md
Updates our status badge from Travis to Circle in the README, and remove old guidance for webpack v5 compatibility that was resolved in #707 and #733
> Docs: Update README & FAQ

- src/composer.ts
a Transaction object will make it here but its not clear it needs a TransactionWithSigner
> docs: fix error message 

- .test-env
- src/client/v2/serviceClient.ts
- tests/9.Client.ts
- tests/cucumber/steps/index.js
- tests/cucumber/steps/steps.js
- tests/cucumber/unit.tags
Implements #635 
This change removes the custom auth headers from requests for all of kmd, algod, and indexer clients. 
After removing this we should be sending only standard headers in requests which should avoid the preflight queries mentioned in 635.
I've added cucumber tests in https://github.com/algorand/algorand-sdk-testing/pull/282 and one test in `tests/9.Client.ts`
> Client: Don't send auth header when token is empty

- .test-env
- src/client/v2/algod/models/types.ts
- tests/cucumber/integration.tags
- tests/cucumber/steps/steps.js
Update model file from https://github.com/algorand/go-algorand/pull/5354/ feature introduction.
> Algod: Simulation run with extra budget per transaction group

- .test-env
To improve visibility of C.I. build failures, utilize new logging capabilities in the sandbox (https://github.com/algorand/sandbox/pull/181) and set `VERBOSE_HARNESS=1`.
In particular we can now see:
* traces of the `docker compose up` command
* dumped `docker-compose logs` for:
* indexer-db
* algod
* indexer
For more information about the effects of this PR on testing in C.I. see the sibling go-sdk pr: https://github.com/algorand/go-algorand-sdk/pull/540
> Enhancement: Verbose Harness

- src/client/v2/algod/algod.ts
- src/client/v2/algod/getLedgerStateDelta.ts
- src/client/v2/algod/getLedgerStateDeltaForTransactionGroup.ts
- src/client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.ts
- src/client/v2/algod/models/types.ts
- src/client/v2/indexer/models/types.ts
- tests/cucumber/steps/steps.js
- tests/cucumber/unit.tags
Adds new APIs to the algod client:
* `/v2/deltas/{round}`
* `/v2/deltas/{round}/txn/group`
* `/v2/deltas/txn/group/{id}`
Implements the new cucumber tests for the above as well.
> algod: Add state delta APIs

- package-lock.json
- package.json
- src/client/urlTokenBaseHTTPClient.ts
at the @thencc we're using the js algosdk in cloudflare workers' v8 environment for EXTREME server-side benefits. 
by simply updating to [`cross-fetch` v4](https://www.npmjs.com/package/cross-fetch/v/4.0.0-alpha.5?activeTab=versions) (currently in alpha), `algosdk` can work in [chrome v8](https://www.cloudflare.com/learning/serverless/glossary/what-is-chrome-v8/) in addition to the usual node + browser envs. this was just recently made available as discussed here: https://github.com/lquixada/cross-fetch/pull/163 
as a byproduct, this PR removes the `mode: "cors"` arg in `algosdk`'s fetch calls as it is not supported by the fetch api available within workers. may i ask what is the real use for this arg anyway?
> fetch: Add Cloudflare Workers support (cross-fetch v4)

- .circleci/config.yml
- package-lock.json
- package.json
Chromedriver v115+ now [ships with Chrome](https://chromedriver.chromium.org/#h.8cjh6c3ay1qq). npm's chromedriver does support this [from v114 and onwards](https://github.com/giggio/node-chromedriver#custom-binaries-url). 
Also updates the CircleCI `browser-tools` orb that fixes a Chrome v115+ issue: https://github.com/CircleCI-Public/browser-tools-orb/issues/81
Fixes CI failures on chrome.
> CICD: Update Chromedriver version and CI orb

- examples/app.ts
- src/encoding/address.ts
- tests/3.Address.js
Adds check when encoding address to string that address is 32 bytes. Also fixes an example that would fail this check because it passes an empty bytearray to encode. Targets the v3 branch.
https://github.com/algorand/js-algorand-sdk/issues/805
> Add address bytes length check in encodeAddress

- .test-env
- .vscode/settings.json
- package-lock.json
- package.json
- src/client/v2/indexer/lookupAccountTransactions.ts
- src/client/v2/indexer/lookupAssetBalances.ts
- src/client/v2/indexer/lookupAssetTransactions.ts
- src/client/v2/indexer/searchAccounts.ts
- src/client/v2/indexer/searchForTransactions.ts
- tests/cucumber/steps/steps.js
> bug-fix: include currency-greater-than param for 0 value

- .circleci/config.yml
- package-lock.json
- package.json
Updates chromedriver package -- Fixes failing Chrome CI setup.
Extra thoughts:
* I don't think `npm install chromedriver@latest` is necessary, because Chrome 115+ pulls up its own version of chromedriver and use that instead: https://chromedriver.chromium.org/downloads/version-selection ~~Here is an instance where an invalid chromedriver version is supplied (v116 is supplied, but the latest version is [115](https://www.npmjs.com/package/chromedriver)), but the CI process still runs up properly: https://github.com/algorand/js-algorand-sdk/pull/776/commits/7569f079b0ca5ef8021a0c69b2ac31005c391372~~
* I wonder if there's a way to remove this dependency altogether, especially since v115+ installs chromedriver alongside chrome, but this might require custom scripts anyway
> CICD: Update chromedriver in package.json to 116+

- .test-env
- src/client/v2/algod/models/types.ts
- tests/cucumber/integration.tags
- tests/cucumber/steps/steps.js
Adds support and tests for the following new simulate features:
* algorand/go-algorand#5658
* algorand/go-algorand#5659
* algorand/go-algorand#5686
See https://github.com/algorand/algorand-sdk-testing/pull/303 for step definitions
REST models updated by rerunning https://github.com/algorand/generator (specifically `scripts/generate_typescript.sh`)
> Simulate: Application State Change and Hash of Executed Bytecode

- .circleci/config.yml
- package-lock.json
- package.json
- tests/cucumber/docker/Dockerfile
Node v16 went EOL on 2023-09-11, and our dependency chromedriver dropped support for it. So we must update to v18 to continue using it (and it's probably a good idea anyway).
> node: Update to node 18, drop support for node 16

- .github/workflows/create-release-pr.yml
NodeJS v16 is no longer supported, so bump the release PR generator appropriately.
Ran `npm install` and `npm test` using v18.
> DevOps: Update release PR generator to nodejs 18

- .eslintrc.js
- package-lock.json
- package.json
- src/client/urlTokenBaseHTTPClient.ts
- tests/cucumber/steps/index.js
- tests/cucumber/unit.tags
With the End of Life of Node 16 and engine set to `>=18`, we can safely use native `fetch`.
Consumers targeting `ie11` or other engines can handle the [fetch pollyfill](https://www.npmjs.com/package/whatwg-fetch).  
Fixes #823 
Relates to #831
> fix: remove cross-fetch

- .test-env
- src/logic/sourcemap.ts
- src/main.ts
- tests/8.LogicSig.ts
- tests/cucumber/steps/steps.js
- tests/cucumber/unit.tags
Improve the source map class and take advantage of column reporting from https://github.com/algorand/go-algorand/pull/5776 to provide more accurate mappings.
Also, rename from `SourceMap` to `ProgramSourceMap` to be more specific. Our source maps are not exactly the same as general source maps, since they map indexes from a binary file (the compiled bytecode) to source locations.
> TEAL Source Map: Improve SourceMap and support columns

- .github/workflows/codegen.yml
- src/client/v2/algod/models/types.ts
- src/client/v2/indexer/models/types.ts
Regenerate models for v2 (develop) branch
> API: Regenerate algod and indexer models

- package-lock.json
- src/client/v2/algod/models/types.ts
Regenerate models for v3 branch
Related to https://github.com/algorand/js-algorand-sdk/pull/845, but for v3
> Regenerate simulate exec trace model

- .circleci/config.yml
- .test-env
- examples/asa.ts
- examples/indexer.ts
- examples/utils.ts
- package-lock.json
- package.json
- tests/cucumber/steps/steps.js
This PR solves two, independent issues which recently caused our CI build to fail.
Chromedriver
===
The chromedriver download URL changed recently, which resulted in our circle CI orb and npm dependency to fail to install it.
This PR updates both of those dependencies, as well as adds conditional logic to our circle CI job to only attempt to install chrome & related tools if it's a browser build. This should make the build more resilient, so that at least some jobs can proceed even if something like this happens again.
Indexer Sync Issue
===
Cucumber integration tests started failing due to a timing issue with indexer catching up to algod.
https://github.com/algorand/algorand-sdk-testing/pull/309 is the test definition fix, and this PR implements the new step which improves …
> Fix: Update chromedriver deps, make install conditional in CI, and fix indexer sync error in cucumber tests

- examples/participation.ts
- src/makeTxn.ts
Fixes a bug in the typing that would make the user think they need to set nonParticipation to `true`. 
Also removed `nonParticipation: true` from the example file.
```ts
algosdk.makeKeyRegistrationTxnWithSuggestedParams(
addr,
undefined,
undefined,
undefined,
undefined,
undefined,
undefined,
suggestedParams,
undefined,
false,
undefined
)
```
```
No overload matches this call.
Overload 1 of 2, '(from: string, note: Uint8Array | undefined, voteKey: string | Uint8Array, selectionKey: string | Uint8Array, voteFirst: number, voteLast: number, voteKeyDilution: number, suggestedParams: SuggestedParams, rekeyTo?: string | undefined, nonParticipation?: false | undefined, stateProofKey?: string | ... 1 more ... | undefined): Transaction', gave the following error.
Argument of type 'undefined' is …
```
> fix: allow either boolean value for nonParticipation offline keyregs

- src/abi/contract.ts
- src/abi/event.ts
- src/abi/interface.ts
- src/abi/method.ts
Adds ARC28 (events) and ARC22 (readonly) to ABI-related interfaces
> feat: add ARC22 and ARC28 interfaces for ABI contracts and methods

- src/client/v2/algod/models/types.ts
Regenerates models to include new simulate option introduced in https://github.com/algorand/go-algorand/pull/5942
> Algod: Regenerate models to include new simulate option

- examples/app.ts
- examples/atc.ts
- examples/indexer.ts
- examples/lsig.ts
- examples/overview.ts
- examples/utils.ts
- src/client/v2/algod/models/types.ts
- src/client/v2/indexer/models/types.ts
- src/dryrun.ts
- tests/cucumber/steps/steps.js
Algod types TEAL byte keys and byte values as strings and base64 encodes them in responses. There was some discussion in https://github.com/algorand/go-algorand/pull/5492 about changing the types on algod, but we decided against it.
This PR updates the types client side so that users don't need to manually decode base64 strings.
A few byte conversion operations were cleaned up as well in the example files.
Relies on https://github.com/algorand/generator/pull/79 to update the generated REST models.
> REST API TEAL bytes fix

- src/client/baseHTTPClient.ts
- src/client/client.ts
- src/client/urlTokenBaseHTTPClient.ts
- src/client/v2/algod/compile.ts
- src/client/v2/algod/disassemble.ts
- src/client/v2/algod/dryrun.ts
- src/client/v2/algod/sendRawTransaction.ts
- src/client/v2/algod/setBlockOffsetTimestamp.ts
- src/client/v2/algod/setSyncRound.ts
- src/client/v2/algod/simulateTransaction.ts
- src/client/v2/algod/unsetSyncRound.ts
- src/client/v2/jsonrequest.ts
- tests/9.Client.ts
- tests/mocha.js
When making requests, exposes an additional options object that can be passed through to the underlying `BaseHTTPClient`. For the default `URLTokenBaseHTTPClient`, this is treated as additional options to pass to the `fetch` network call.
Fixes #858
> 3.0.0: Add ability to pass through fetch options

- .github/workflows/create-release-pr.yml
#889 was created using the create release PR github action, but it deletes the entire `dist` folder when it shouldn't. With v3, a file permanently exists in the `dist` folder and we don't want to remove it.
> Fix: Don't delete `dist` folder when creating release PR

- .github/workflows/create-release-pr.yml
Use the prerelease tag when generating the changelog for release PRs.
If a prerelease version is specified, right now that is not used when generating the release PR with the planned version tag.
For example, that causes this statement to be at the end of the changelog:
> **Full Changelog**: https://github.com/algorand/js-algorand-sdk/compare/v2.9.0...v3.0.0
Instead of:
> **Full Changelog**: https://github.com/algorand/js-algorand-sdk/compare/v2.9.0...v3.0.0-beta.1
I manually updated it in #891, but it would be nice to fix this at the source
> Release PR Generation: Use prerelease tag in changelog generation

- tests/cucumber/steps/steps.js
Fix the following failure in browser environment:
```
Error: Error from test 'then the parsed Get Block response should have heartbeat address {string}': ReferenceError: skip is not defined
ReferenceError: skip is not defined
at Object.eval (eval at executeScript (:1:1), <anonymous>:1363:13)
at eval (eval at <anonymous> (:1:1), <anonymous>:8:40)
```
> cucumber: fix miissing skip in browsers

- src/abi/abi_type.ts
- tests/10.ABI.ts
Allows `Address` to be an acceptable ABIValue and properly handles `Address` in `ABIAddressType.encode`
> feat: add Address as an ABIValue and handle encoding an Address

- src/client/v2/algod/block.ts
- src/client/v2/algod/models/types.ts
- tests/cucumber/steps/steps.js
This PR adds support for a new header-only=true parameter to the '/v2/block/{round}' endpoint. Includes support for cross-SDK test cases.
> API: Support for header-only flag on /v2/block algod endpoint (v2.x backport)

- Makefile
- tests/cucumber/docker/Dockerfile
This PR makes the following fixes to the cucumber docker container:
- updates ubuntu to newer LTS
- forces docker-build to amd64, to allow for google-chrome-stable install
- cleans up install for firefox and chrome
- update node install to v22
- removes broken $HOME variable
Known test failures show up (but tests run) for `make docker-test`
> DevOps: Fix docker-test by locking to amd64 and updating dependencies

- README.md
Use absolute link in the README when linking to migration guide so it works properly on the typedoc site. 
Note that if we wanted to maintain a relative link we could either update TypeDoc and the plugins to get support for external documents or use a plugin to pull in the markdown, but this seems like the simpler solution considering churn rate will probably be low on the migration guide
> docs: fix link in README so it works in typedoc

- .circleci/config.yml
- package-lock.json
- tests/cucumber/docker/Dockerfile
- tests/cucumber/steps/index.js
- tests/cucumber/steps/steps.js
- tests/mocha.js
Add appropriate waits/sleeps to allow for box pagination API calls to return all expected/persisted results in application cucumber tests.
Set Node version in Circle build to v22, update Ubuntu image for builds to noble/24.04, and update selenium/geckodriver for compatibility with Ubuntu 24.
> Build: Fix Box API Pagination-dependent integration tests

- README.md
Port of (#947) onto the main branch after git flow retirement.
> Docs: fix link in README so it works in typedoc 

- .github/workflows/ci-pr.yml
- Makefile
- package-lock.json
- package.json
This is an implementation of unit and integration tests in GitHub Actions. Google Chrome and Firefox appear to already be installed in the ubuntu-24.04 image, so no need to install them here.
Chromedriver requires an explanation. Because we have it as a devDependency, the value for it can be overridden by what is in package.json. Because this is just for testing, We install a version of chromedriver that matches the installed google-chrome.
Oddly geckodriver doesn't appear to show any compatibility issues, but if it does later, we may have to revisit. (The driver version does not match the browser version, so we may have to figure out the right versioning.)
Some other changes:
- Removed interactive mode from dockerfile, as it was unnecessary
- Created a ci-test target that does not build …
> CICD: implement tests in GitHub Actions

- src/encoding/schema/bytearray.ts
The indexer API supports retrieving deleted applications by suppling the `include-all=true` param when calling `/v2/applications/{applicationId}`, however when fetching a deleted application via the algosdk using `indexer.lookupApplications(applicationId).includeAll(true).do()` it throws an error "Invalid byte array: (object) null".
This error is due to the indexer API returning a `null` value for the `approval-program` and `clear-state-program`, however those values are deserialized using the `ByteArraySchema` which expects a base64 encoded bytes value. This can be observed in this application https://mainnet-idx.algonode.cloud/v2/applications/2365972864?include-all=true
This PR updates the ByteArraySchema JSON deserializer to handle `null` or `undefined` values and maps them to the …
> fix: handle null values when deserializing byte arrays

- CODEOWNERS
- README.md
Since tests were shifted to GitHub Actions, this PR swaps the status badge to reflect this.
Additionally, the CODEOWNERS file was removed.
See if badge displays, and verify tests (but no code changes so should pass).
> README: update CI badge

- src/appAccess.ts
- src/makeTxn.ts
- src/transaction.ts
- src/types/transactions/base.ts
- tests/5.Transaction.ts
Add `txn.Access` support similarly to other SDKs and tests.
The caveat is JS SDK uses the same types for deflated and inflated representation of box references (and so that holdings and locals inside resource reference) and accepts weakly typed addresses (`string`, `Address`).
This type acrobatics while maintaining proper inflated/deflated versions contributed to the PR size.
> types: add txn access

- src/appAccess.ts
- tests/5.Transaction.ts
> Apps: In access, addresses need to be checked for nil cases and compared via equals() rather than reference equality.
